version: "3.8"

volumes:
  cs345-neo4j-data:

services:
  cs345-neo4j:
    container_name: cs345-neo4j
    image: neo4j:5.5-enterprise
    hostname: cs345-neo4j
    restart: "no"
    expose:
      - 7474
      - 7687
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - cs345-neo4j-data:/data
      - ./plugins:/plugins
      - ./setup:/setup
    environment:
      - NEO4J_AUTH=neo4j/cs345gnn
      - NEO4J_PLUGINS='["graph-data-science", "apoc"]'
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_security_procedures_allowlist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*